### ISSUE TITLE
WL Monitor for Alexa

### ISSUE THREAD

**Issue by Zacki84** [mabe-at/WL-Monitor-Pi#1]
Hi

I really like this project, thats why I want to ask if someone can help me building a alexa skill. I'm a nope in skill programming, but it would be great to ask: Alexa, when comes the next bus? Or Alexa, when comes the next subway?
And Alexa answers the minutes to wait for RBL you setup in skill

Thanks a lot!!!

**Comment by mabe-at** [comment]
A simple Alexa skill is now available.
https://github.com/mabe-at/WL-Monitor-Pi-Alexa

**Comment by Zacki84** [comment]
Hallo Matthias

Ich habe es endlich geschafft meinen Raspberry wieder fit zu bekommen und
die neueste Alexa SDK zu installieren.
Nun wollte ich nun deinen Skill aktivieren. Hat auch alles soweit ganz gut
funktioniert.
Nur beim Testen mit ngrok, bekomme ich immer die Fehlermeldung: POST /  405
METHOD NOT ALLOWED
Weißt du zufällig was das für ein Fehler ist? Google konnte mir leider auch
nicht weiterhelfen.

Auf meinem Raspberry läuft aber auch ein Apache Server. Weißt du ob ich den
anstatt ngrok verwenden kann bzw wenn ja wie?

Vielen Dank
LG René

Am So., 20. Mai 2018 um 21:10 Uhr schrieb Matthias Bendel <
notifications@github.com>:

**Comment by mabe-at** [comment]
Hallo!

Leider eine sehr verspätete Antwort.

Zunächst bitte poste Fragen zur Alexa-Skill hier: https://github.com/mabe-at/WL-Monitor-Pi-Alexa
Ich habe den Verdacht, dass der angegebene Endpoint womöglich nicht stimmt. Ev. Port (Apache) oder die URL stimmt nicht.

Genaueres kann ich dazu aber auch nicht sagen.

LG Matthias
